version: '3'

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres:11.2-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: sbg_rj
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  web:
    build: .
    command: >
      bash -c "python manage.py collectstatic --noinput
      && python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/web
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: )+_5hm21n_$@p0kofd5e4bq@ivl9s0=brcazqo2qouhpd6roaw
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: sbg_rj
      DB_HOST: postgres
      DB_PORT: 5432
    depends_on:
      - postgres