version: '3'

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres:11.2-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: sbg_rj
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  web:
    env_file:
      - app.env
    depends_on:
      - postgres
    image: sbg-rj
    ports:
      - "8000:8000"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/web
    command: >
      bash -c "python manage.py migrate && 
               python manage.py collectstatic &&
               python manage.py runserver 0.0.0.0:8000"
    environment:
      SECRET_KEY: o&8zwmdqj!-ecoct8^*b+nlkc%-3r=^@fu^&=ovwz1%+k080bw
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: sbg_rj
      DB_HOST: postgres
      DB_PORT: 5432