# Generated by Django 2.2 on 2019-04-07 12:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=50, null=True, verbose_name='Sobrenome')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('password', models.CharField(max_length=128, verbose_name='Senha')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('is_staff', models.BooleanField(default=True, verbose_name='Funcionário?')),
                ('is_superuser', models.BooleanField(default=True, verbose_name='Administrador?')),
                ('last_login', models.DateTimeField(null=True, verbose_name='Ultimo login')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultima atualização')),
                ('groups', models.ManyToManyField(blank=True, help_text='Grupo ao qual o usuário pertence. O usuário recebe todas as permissões dos grupos ao qual ele pertence.', related_name='user_groups', related_query_name='user', to='auth.Group', verbose_name='Grupos de usuário')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Permissões específicas do usuário.', related_name='user_permissions', related_query_name='user', to='auth.Permission', verbose_name='Permissões do usuário')),
            ],
            options={
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('image', models.ImageField(upload_to='media/events/%Y-%m-%d', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'svg'], 'Formato de imagem inválido (.png, .jpg, .svg)')], verbose_name='Imagem')),
                ('icon', models.ImageField(upload_to='media/events/%Y-%m-%d', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'svg'], 'Formato de ícone inválido (.png, .jpg, .svg)')], verbose_name='Ícone')),
                ('apresentation', models.FileField(upload_to='media/events/%Y-%m-%d', validators=[django.core.validators.FileExtensionValidator(['pdf', 'ppt', 'pptx'], 'Formato de apresentação inválido (.pdf, .ppt, .pptx)')], verbose_name='Apresentação')),
                ('starts_at', models.DateTimeField(verbose_name='Data de início')),
                ('ends_at', models.DateTimeField(verbose_name='Data de término')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultima atualização')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuário responsável pela criação do registro (evento).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_creator_set', to=settings.AUTH_USER_MODEL, verbose_name='Criador')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Usuário responsável pela ultima atualização do registro (evento).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_updater_set', to=settings.AUTH_USER_MODEL, verbose_name='Atualizador')),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=50, null=True, verbose_name='Sobrenome')),
                ('role', models.CharField(max_length=50, verbose_name='Cargo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('started_at', models.DateTimeField(verbose_name='Data de início')),
                ('ends_at', models.DateTimeField(verbose_name='Data de término')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultima atualização')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuário responsável pela criação do registro (diretor).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='director_creator_set', to=settings.AUTH_USER_MODEL, verbose_name='Criador')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Usuário responsável pela ultima atualização do registro (diretor).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='director_updater_set', to=settings.AUTH_USER_MODEL, verbose_name='Atualizador')),
            ],
        ),
    ]
