# Generated by Django 2.2 on 2019-04-04 14:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=50, null=True, verbose_name='Sobrenome')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('password', models.CharField(max_length=128, verbose_name='Senha')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('is_staff', models.BooleanField(default=True, verbose_name='Funcionário?')),
                ('is_superuser', models.BooleanField(default=True, verbose_name='Administrador?')),
                ('last_login', models.DateTimeField(null=True, verbose_name='Ultimo login')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultima atualização')),
                ('groups', models.ManyToManyField(blank=True, help_text='Grupo ao qual o usuário pertence. O usuário recebe todas as permissões dos grupos ao qual ele pertence.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='Grupos de usuário')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Permissões específicas do usuário.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='Permissões do usuário')),
            ],
            options={
                'verbose_name_plural': 'Users',
            },
        ),
    ]
