# Generated by Django 2.2 on 2019-04-06 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Grupo ao qual o usuário pertence. O usuário recebe todas as permissões dos grupos ao qual ele pertence.', related_name='user_groups', related_query_name='user', to='auth.Group', verbose_name='Grupos de usuário'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Permissões específicas do usuário.', related_name='user_permissions', related_query_name='user', to='auth.Permission', verbose_name='Permissões do usuário'),
        ),
    ]
