# Generated by Django 2.2 on 2019-04-06 00:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=50, null=True, verbose_name='Sobrenome')),
                ('role', models.CharField(max_length=50, verbose_name='Cargo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('started_at', models.DateTimeField(verbose_name='Data de início')),
                ('ends_at', models.DateTimeField(verbose_name='Data de término')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultima atualização')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuário responsável pela criação do registro (diretor).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_creator_set', to=settings.AUTH_USER_MODEL, verbose_name='Criador')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Usuário responsável pela ultima atualização do registro (diretor).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_updater_set', to=settings.AUTH_USER_MODEL, verbose_name='Atualizador')),
            ],
        ),
    ]
