# Generated by Django 2.2 on 2019-04-07 14:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='director',
            options={'verbose_name': 'Diretor', 'verbose_name_plural': 'Diretores'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AlterField(
            model_name='event',
            name='apresentation',
            field=models.FileField(upload_to='media/events/%Y-%m-%d/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'ppt', 'pptx'], 'Formato de apresentação inválido (.pdf, .ppt, .pptx)')], verbose_name='Apresentação'),
        ),
        migrations.AlterField(
            model_name='event',
            name='icon',
            field=models.ImageField(upload_to='media/events/%Y-%m-%d/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'], 'Formato de ícone inválido (.png, .jpg, jpeg)')], verbose_name='Ícone'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(upload_to='media/events/%Y-%m-%d/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'], 'Formato de imagem inválido (.png, .jpg, jpeg)')], verbose_name='Imagem'),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='Título da Notícia')),
                ('resume', models.TextField(verbose_name='Resumo da Notícia')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('publish_date', models.DateTimeField(verbose_name='Data da Notícia')),
                ('image', models.ImageField(upload_to='media/news/%Y-%m-%d', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'], 'Formato de imagem inválido (.png, .jpg, .jpeg)')], verbose_name='Imagem')),
                ('icon', models.ImageField(upload_to='media/news/%Y-%m-%d', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'], 'Formato de imagem inválido (.png, .jpg, .jpeg)')], verbose_name='Ícone')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultima atualização')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuário responsável pela criação do registro (Notícia).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_creator_set', to=settings.AUTH_USER_MODEL, verbose_name='Criador')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Usuário responsável pela ultima atualização do registro (Notícia).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_updater_set', to=settings.AUTH_USER_MODEL, verbose_name='Atualizador')),
            ],
            options={
                'verbose_name': 'Notícia',
                'verbose_name_plural': 'Notícias',
            },
        ),
    ]
