# Generated by Django 2.2 on 2019-04-07 14:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190407_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('image', models.ImageField(upload_to='media/products/%Y-%m-%d/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'], 'Formato de imagem inválido (.png, .jpg, jpeg)')], verbose_name='Imagem')),
                ('icon', models.ImageField(upload_to='media/products/%Y-%m-%d/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'], 'Formato de ícone inválido (.png, .jpg, jpeg)')], verbose_name='Ícone')),
                ('price_associated', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Preço de associado')),
                ('price_non_associated', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Preço de não associado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultima atualização')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuário responsável pela criação do registro (produto).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_creator_set', to=settings.AUTH_USER_MODEL, verbose_name='Criador')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Usuário responsável pela ultima atualização do registro (produto).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_updater_set', to=settings.AUTH_USER_MODEL, verbose_name='Atualizador')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
