# Generated by Django 2.2 on 2019-04-11 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190411_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slideshow',
            field=models.BooleanField(default=False, help_text='Selecione essa opção se deseja que o evento apareça na HomePage.', verbose_name='Aparece no Slideshow?'),
        ),
    ]
