# Generated by Django 2.2 on 2019-04-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_event_slideshow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slideshow',
            field=models.BooleanField(default=False, help_text='Selecione essa opção se deseja que o evento apareça na HomePage.', verbose_name='Slideshow'),
        ),
    ]
