# Generated by Django 2.2 on 2019-04-13 17:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190413_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, help_text='Utilizado para que o link da página fique torne-se fácil de ler por um humano', unique=True, verbose_name='Slogan da página'),
            preserve_default=False,
        ),
    ]
