# Generated by Django 2.2 on 2019-04-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_event_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(help_text='Utilizado para que o link da página fique torne-se fácil de ler por um humano', max_length=500, unique=True, verbose_name='Slogan da página'),
        ),
    ]
