# Generated by Django 2.2 on 2019-04-14 18:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20190413_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, help_text='Utilizado para que o link da página torne-se fácil de ler por um humano', max_length=500, unique=True, verbose_name='Slogan da página'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(help_text='Utilizado para que o link da página torne-se fácil de ler por um humano', max_length=500, unique=True, verbose_name='Slogan da página'),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(help_text='Utilizado para que o link da página torne-se fácil de ler por um humano', max_length=500, unique=True, verbose_name='Slogan da página'),
        ),
    ]
