# Generated by Django 2.2 on 2019-04-16 13:27

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20190414_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='gallery/%Y-%m-%d', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'], 'Formato de imagem inválido (.png, .jpg, .jpeg)')], verbose_name='Imagem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gallery',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, help_text='Utilizado para que o link da página torne-se fácil de ler por um humano', max_length=500, unique=True, verbose_name='Slogan da página'),
            preserve_default=False,
        ),
    ]
