# Generated by Django 2.2 on 2019-04-17 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20190416_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='category',
            field=models.CharField(choices=[('Anais de Simpósio', 'Anais de Simpósio'), ('Anais de Congresso', 'Anais de Congresso'), ('Clippings  ', 'Clippings')], max_length=50, null=True, verbose_name='Categoria'),
        ),
    ]
