# Generated by Django 2.2 on 2019-04-21 20:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20190419_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='resume',
            field=models.TextField(default=django.utils.timezone.now, help_text='Utilizado no slideshow e listas', verbose_name='Resumo'),
            preserve_default=False,
        ),
    ]
