# Generated by Django 2.2 on 2019-04-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_event_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='resume',
            field=models.CharField(max_length=150, verbose_name='Resumo'),
        ),
    ]
