# Generated by Django 2.2 on 2019-04-21 20:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20190421_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slideshow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='events/%Y-%m-%d/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'], 'Formato de imagem inválido (.png, .jpg, jpeg)')], verbose_name='Imagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultima atualização')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuário responsável pela criação do registro (slide).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slide_creator_set', to=settings.AUTH_USER_MODEL, verbose_name='Criador')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Usuário responsável pela ultima atualização do registro (slide).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slide_updater_set', to=settings.AUTH_USER_MODEL, verbose_name='Atualizador')),
            ],
            options={
                'verbose_name': 'Slideshow',
                'verbose_name_plural': 'Slideshow',
            },
        ),
    ]
