# Generated by Django 2.2 on 2019-04-21 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20190421_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='resume',
            field=models.CharField(max_length=250, verbose_name='Resumo'),
        ),
        migrations.AlterField(
            model_name='slideshow',
            name='resume',
            field=models.CharField(max_length=250, verbose_name='Resumo'),
        ),
    ]
