# Generated by Django 2.2 on 2019-04-22 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20190421_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='slideshow',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Título'),
        ),
    ]
