# Generated by Django 2.2 on 2019-04-23 16:07

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20190422_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='Descrição'),
        ),
    ]
