# Generated by Django 2.2 on 2019-05-15 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20190423_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slideshow',
            name='resume',
            field=models.CharField(max_length=500, verbose_name='Resumo'),
        ),
    ]
