# Generated by Django 2.2 on 2019-05-15 02:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20190515_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='apresentation',
            field=models.FileField(null=True, upload_to='events/%Y-%m-%d/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'ppt', 'pptx'], 'Formato de apresentação inválido (.pdf, .ppt, .pptx)')], verbose_name='Apresentação'),
        ),
    ]
