# Generated by Django 2.2 on 2019-06-11 13:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20190522_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='photos/%Y-%m-%d/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'], 'Formato de imagem inválido (.png, .jpg, jpeg)')], verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='slideshow',
            name='image',
            field=models.ImageField(upload_to='slideshow/%Y-%m-%d/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'], 'Formato de imagem inválido (.png, .jpg, jpeg)')], verbose_name='Imagem'),
        ),
    ]
