from .director import DirectorCreateTestCase
from .event import EventCreateTestCase
from .gallery import GalleryCreateTestCase
from .news import NewsCreateTestCase
from .photo import PhotoCreateTestCase
from .product import ProductCreateTestCase
from .publication import PublicationCreateTestCase
from .slideshow import SlideshowCreateTestCase
from .user import UserCreateTestCase
